name: Pipline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:



jobs:
  Run_Unit_Tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@ec92e829475ac0c2315ea8f9eced72db85bb337a
        with:
          gradle-version: '8.6'

      - name: Run Unit Tests
        run: ./gradlew test

  lint_checkstyle:
    runs-on: ubuntu-latest
    needs: Run_Unit_Tests
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@ec92e829475ac0c2315ea8f9eced72db85bb337a
        with:
          gradle-version: '8.6'

      - name: Run Checkstyle
        run: ./gradlew checkstyleMain checkstyleTest

  hadolint:
    runs-on: ubuntu-latest
    needs: lint_checkstyle
    permissions:
      contents: read

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install hadolint
        run: |
          wget -O hadolint "https://github.com/hadolint/hadolint/releases/download/v2.7.0/hadolint-Linux-x86_64" && \
          chmod +x hadolint && \
          sudo mv hadolint /usr/local/bin/hadolint

      - name: Run hadolint
        run: hadolint Dockerfile

  build_jar_file:
    runs-on: ubuntu-latest
    needs: hadolint
    permissions:
      contents: read
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@ec92e829475ac0c2315ea8f9eced72db85bb337a
        with:
          gradle-version: '8.6'

      - name: Build with Gradle
        run: ./gradlew bootJar

  build_and_deploy_docker_image:
    runs-on: ubuntu-latest
    needs: build_jar_file
    permissions:
      contents: read

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@ec92e829475ac0c2315ea8f9eced72db85bb337a
        with:
          gradle-version: '8.6'

      - name: Build with Gradle
        run: ./gradlew bootJar

      - name: Log into GitHub Container Registry
        run: echo ${{ secrets.efnan}} | docker login ghcr.io -u ${{ github.actor }} --password-stdin



